name: Deploy to GitHub Pages

on:
  push: 
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write # HTMLを書き込むために 'write' に変更
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy: # ジョブを1つに統合
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- ここからが追加・変更部分 ---
      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          # ルート以外の全てのindex.mdを検索し、同じディレクトリにindex.htmlとして変換
          find . -type f -name "index.md" -not -path "./index.md" | while read mdfile; do
            dir=$(dirname "$mdfile")
            # style.cssを適用し、目次も自動生成する例
            pandoc "$mdfile" -o "$dir/index.html" --standalone --css "../style.css" --toc
            echo "Converted $mdfile to $dir/index.html"
          done
      # --- ここまでが追加・変更部分 ---

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build search index
        run: npm run build:search

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
